"""Central configuration for GPU optimization parameters."""

GPU_TRANSFER_THRESHOLD = 8
VEC_ENV_COUNT = 16
BATCH_SIZE = 256
TRAIN_EVERY_K = 1
TRAIN_UPDATES_PER_TRIGGER = 8
THREAD_POOL_WORKERS = 8
REPLAY_CAPACITY = 40000
CUPY_MEMPOOL_LIMIT_BYTES = 4 * 1024 ** 3
COMM_DECISION_INTERVAL_STEPS = 8
COMM_FASTFADING_UPDATE_INTERVAL_STEPS = 8
COMM_METRICS_UPDATE_INTERVAL_STEPS = 8
COMM_AGENT_SKIP_EMBEDDING_STEPS = 23
COMM_AGENT_GRAPH_REFRESH_STEPS = 400
