#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Create a journal-style V2V-focused summary figure for progressive ablation.

Default inputs:
  runs/ablation_progressive_merged/progressive_mean_std.csv
  runs/ablation_progressive_merged/progressive_delta_prev_mean_std.csv

Default output basename:
  figures/fig6_ablation_metrics
"""

from __future__ import annotations

import argparse
import csv
from io import BytesIO
from pathlib import Path
from typing import Dict, List

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image


STAGE_LABELS = {
    "none": "Base",
    "plus_urgency": "+Urgency",
    "plus_rb_balance": "+RB\nBalancing",
    "plus_conflict": "+Conflict\nGuidance",
    "plus_attn_reg": "+Attention\nReg.",
    "full": "+Adaptive\nRe-pruning",
}

MODULE_LABELS = {
    "plus_urgency": "Urgency",
    "plus_rb_balance": "RB\nBalancing",
    "plus_conflict": "Conflict\nGuidance",
    "plus_attn_reg": "Attention\nReg.",
    "full": "Adaptive\nRe-pruning",
}


def read_csv(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def as_float(row: Dict[str, str], key: str) -> float:
    return float(row[key])


def stage_label(stage: str) -> str:
    return STAGE_LABELS.get(stage, stage)


def module_label(stage: str) -> str:
    return MODULE_LABELS.get(stage, stage)


def annotate_bars(ax: plt.Axes, bars, values: List[float], errors: List[float], fmt: str, dy: float) -> None:
    for rect, value, err in zip(bars, values, errors):
        ax.text(
            rect.get_x() + rect.get_width() / 2.0,
            rect.get_height() + err + dy,
            fmt.format(value),
            ha="center",
            va="bottom",
            fontsize=9,
            color="#1F2937",
        )


def save_figure(fig: plt.Figure, out_path: Path, dpi: int = 1000) -> List[Path]:
    png_path = out_path.with_suffix(".png")
    pdf_path = out_path.with_suffix(".pdf")
    tiff_path = out_path.with_suffix(".tiff")

    fig.savefig(png_path, dpi=dpi, bbox_inches="tight")
    fig.savefig(pdf_path, dpi=dpi, bbox_inches="tight")

    buf = BytesIO()
    fig.savefig(buf, format="png", dpi=dpi, bbox_inches="tight")
    buf.seek(0)
    with Image.open(buf) as im:
        im.save(tiff_path, compression="tiff_lzw", dpi=(dpi, dpi))
    buf.close()

    return [png_path, pdf_path, tiff_path]


def save_axis_figure(fig: plt.Figure, ax: plt.Axes, out_path: Path, dpi: int = 1000) -> List[Path]:
    png_path = out_path.with_suffix(".png")
    pdf_path = out_path.with_suffix(".pdf")
    tiff_path = out_path.with_suffix(".tiff")

    fig.canvas.draw()
    renderer = fig.canvas.get_renderer()
    bbox = ax.get_tightbbox(renderer).expanded(1.03, 1.06)
    bbox_inches = bbox.transformed(fig.dpi_scale_trans.inverted())

    fig.savefig(png_path, dpi=dpi, bbox_inches=bbox_inches)
    fig.savefig(pdf_path, dpi=dpi, bbox_inches=bbox_inches)

    buf = BytesIO()
    fig.savefig(buf, format="png", dpi=dpi, bbox_inches=bbox_inches)
    buf.seek(0)
    with Image.open(buf) as im:
        im.save(tiff_path, compression="tiff_lzw", dpi=(dpi, dpi))
    buf.close()

    return [png_path, pdf_path, tiff_path]


def annotate_delta_bars(ax: plt.Axes, bars, values: List[float], errors: List[float], fmt: str, dy: float) -> None:
    for rect, value, err in zip(bars, values, errors):
        y = rect.get_height() + err + dy if rect.get_height() >= 0 else rect.get_height() - err - dy
        va = "bottom" if rect.get_height() >= 0 else "top"
        ax.text(
            rect.get_x() + rect.get_width() / 2.0,
            y,
            fmt.format(value),
            ha="center",
            va=va,
            fontsize=9,
            color="#1F2937",
        )


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot a V2V-focused summary figure for progressive ablation.")
    parser.add_argument(
        "--mean-csv",
        type=str,
        default="runs/ablation_progressive_merged/progressive_mean_std.csv",
        help="Mean/std CSV generated by merge_progressive_ablation.py",
    )
    parser.add_argument(
        "--delta-csv",
        type=str,
        default="runs/ablation_progressive_merged/progressive_delta_prev_mean_std.csv",
        help="Delta-prev CSV generated by merge_progressive_ablation.py",
    )
    parser.add_argument(
        "--out",
        type=str,
        default="figures/fig6_ablation_metrics",
        help="Output basename or figure path",
    )
    args = parser.parse_args()

    mean_rows = read_csv(Path(args.mean_csv))
    delta_rows = read_csv(Path(args.delta_csv))
    out_path = Path(args.out)
    if out_path.suffix.lower() in {".png", ".pdf", ".tif", ".tiff"}:
        out_path = out_path.with_suffix("")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    stage_names = [row["stage"] for row in mean_rows]
    labels = [stage_label(s) for s in stage_names]
    x = np.arange(len(labels))

    v2v_mean = [as_float(row, "final_v2v_mean") for row in mean_rows]
    v2v_std = [as_float(row, "final_v2v_std") for row in mean_rows]
    delta_labels = [module_label(row["stage"]) for row in delta_rows]
    xd = np.arange(len(delta_labels))
    dv2v_mean = [as_float(row, "delta_v2v_mean") for row in delta_rows]
    dv2v_std = [as_float(row, "delta_v2v_std") for row in delta_rows]
    best_v2v_idx = int(np.argmax(v2v_mean))
    best_delta_idx = int(np.argmax(dv2v_mean))

    base_bar = "#D7E3F1"
    best_bar = "#325D79"
    full_bar = "#547792"
    pos_bar = "#CFE9D7"
    best_delta_bar = "#3F7D58"
    neg_bar = "#F2C6B4"
    edge = "#40556B"

    abs_colors = [base_bar for _ in labels]
    if "full" in stage_names:
        abs_colors[stage_names.index("full")] = full_bar
    abs_colors[best_v2v_idx] = best_bar

    delta_v2v_colors = [pos_bar if val >= 0 else neg_bar for val in dv2v_mean]
    delta_v2v_colors[best_delta_idx] = best_delta_bar

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10.8, 4.4))

    bars1 = ax1.bar(x, v2v_mean, yerr=v2v_std, capsize=4, color=abs_colors, edgecolor=edge, linewidth=1.0)
    ax1.set_ylabel("Normalized V2V score")
    ax1.set_xticks(x)
    ax1.set_xticklabels(labels)
    ax1.grid(axis="y", alpha=0.25)
    ax1.set_ylim(0.20, max(v2v_mean) + max(v2v_std) + 0.03)
    annotate_bars(ax1, bars1, v2v_mean, v2v_std, "{:.3f}", 0.003)
    ax1.tick_params(axis="x", labelsize=9)
    ax1.tick_params(axis="y", labelsize=9)

    bars2 = ax2.bar(xd, dv2v_mean, yerr=dv2v_std, capsize=4, color=delta_v2v_colors, edgecolor="#355070", linewidth=1.0)
    ax2.axhline(0.0, color="#6B7280", linewidth=1.0)
    ax2.set_ylabel("Delta V2V vs previous stage")
    ax2.set_xticks(xd)
    ax2.set_xticklabels(delta_labels)
    ax2.grid(axis="y", alpha=0.25)
    ymin3 = min(-0.01, min(v - e for v, e in zip(dv2v_mean, dv2v_std)) - 0.002)
    ymax3 = max(dv2v_mean) + max(dv2v_std) + 0.015
    ax2.set_ylim(ymin3, ymax3)
    annotate_delta_bars(ax2, bars2, dv2v_mean, dv2v_std, "{:+.3f}", 0.003)
    ax2.tick_params(axis="x", labelsize=9)
    ax2.tick_params(axis="y", labelsize=9)

    plt.tight_layout(pad=1.0, w_pad=1.4)
    saved_paths = save_figure(fig, out_path, dpi=1000)
    saved_paths += save_axis_figure(
        fig,
        ax1,
        out_path.parent / "fig6a_ablation_final_score",
        dpi=1000,
    )
    saved_paths += save_axis_figure(
        fig,
        ax2,
        out_path.parent / "fig6b_ablation_incremental_gain",
        dpi=1000,
    )
    plt.close(fig)
    for saved_path in saved_paths:
        print(f"[Saved] {saved_path}")


if __name__ == "__main__":
    main()
